### ISSUE TITLE
Error when running Docker Container

### ISSUE THREAD

**Issue by danielslyman** [GlobalCyberAlliance/DomainSecurityScanner#10]
Hey guys,

I am trying to run the docker container but this error pops up:

FTL unable to create config error="open //.config/domain-security-scanner/config.yml: no such file or directory"

Any ideas?

Best,
Daniel

**Comment by wolveix** [comment]
Hey @danielslyman! Sorry about that, there was an oversight in our recently implemented config handling. The issue has been adressed, and the newly built Docker image (which should be available in a few minutes) addresses this issue. 

Thanks for reporting it!

**Comment by danielslyman** [comment]
Thanks a bunch!
