### ISSUE TITLE
Several Win Trojan Detections:  dss-windows-amd64.exe.zip 

### ISSUE THREAD

**Issue by OrlandoNE** [GlobalCyberAlliance/DomainSecurityScanner#12]
Hello - for your awareness regarding executable binaries, the zip-extracted EXE (20.8 MB) for dss-windows-amd64.exe.zip released two days ago at https://github.com/GlobalCyberAlliance/DomainSecurityScanner/releases is triggering the following online malware file checking services:

VirtusTotal - 
Detected  - Trojan.Malware.300983.susgen
https://www.virustotal.com/gui/file/19300db7ce81db811d0bd9af125a406dab57b3dc6391398cbe3c64d88447a1bd

Microsoft Security Intelligence Submission 
Detected - Trojan:Win32/Sabsik.FL.A!ml
[Detected by Microsoft Defender Antivirus](https://www.microsoft.com/en-us/windows/windows-defender?ocid=cx-wdsi-ency)
https://www.microsoft.com/en-us/wdsi/submission/dc12bd13-5ee1-440b-bfd8-f56c6f11511e

Could you please review and advise?

Respectfully,

Orlando Stevenson

[dss-windows-amd64_(infected).zip](https://github.com/GlobalCyberAlliance/DomainSecurityScanner/files/12268277/dss-windows-amd64_.infected.zip)

**Comment by wolveix** [comment]
Hey @OrlandoNE, thanks for bringing this to our attention. I'm not too sure why this would be detected as a trojan, but rest assured that we're looking into it.

**Comment by wolveix** [comment]
@OrlandoNE this seems like nothing more than a false positive. I've checked both the most recent build, and the build before that, and only one provider (MaxSecure) seems to flag the binaries as containing trojans. Our source code is completely open, and you can review the build process here: https://github.com/GlobalCyberAlliance/DomainSecurityScanner/blob/main/.github/workflows/release.yml

Unless you have any other queries or suggestions as to what may be triggering this false positive, I'll close this out. Thanks again!

**Comment by OrlandoNE** [comment]
Hello - thank you for promptly responding and checking into this issue!

My Microsoft submission also came back as a false positive following further review with the following analyst comments:

"t this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.... "

More:  https://www.microsoft.com/en-us/wdsi/submission/dc12bd13-5ee1-440b-bfd8-f56c6f11511e

:)

**Comment by OrlandoNE** [comment]
@wolveix Hello - thank you for promptly responding and checking into this issue!

My Microsoft submission also came back as a false positive following further review with the following analyst comments:

"t this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.... "

More:  https://www.microsoft.com/en-us/wdsi/submission/dc12bd13-5ee1-440b-bfd8-f56c6f11511e
:)
