### ISSUE TITLE
Windows DomainSecurityScanner Pre-Complied Issues with Creating Output File 

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/DomainSecurityScanner#13]
Hello - both the individual and bulk processing using the Windows pre-compiled DSS binary have been interactively returning console results fine so far.  However, when I attempt to write file ("-w") or redirect standard output (using ">"), can't seem to get it to work on Win10 Pro, tried on two systems.   
 
 The "-w" for the below produced a serialized *.yaml filename.  The second with output redirect ">" reported results interactively, put "INF Accepting input from STDIN.." in the file but still only reported results interactively. The testdin.csv file contains three entries in the form of:
    domain1.com
    domain2.com
    domain3.com
    
    
Command line test use:  
     dss scan -t120 -w report.txt -n 1.1.1.1 < testdin.csv
     dss scan -t120 -n 1.1.1.1 < testdin.csv > report.txt
    
  Could you please review and advise?
  
  Respectfully,
  
  Orlando

**Comment by wolveix** [comment]
Hey @OrlandoMD, thanks for taking the time to open this issue.

Your command should look like this:

```
dss scan -t120 -w -n 1.1.1.1 < testdin.csv
```

The `-w` flag doesn't accept a value after specifying it, as it's a simple boolean flag (whether to write to a file, or not). It simply writes the results to a file named after the current unix time at the time the command is run. I do believe that your syntax _does_ make more sense. Perhaps it should be changed so that if `-w` is specified **with** an argument, it'll write to that file instead

**Comment by wolveix** [comment]
@OrlandoMD I've reworked this behaviour to be a little clearer and to follow more common conventions regarding outputting results to a file.

Your command above should now look like this:

```
dss scan -t 120 -n 1.1.1.1 -o report < testdin.csv
```

This will output the domains to files like this:
```
report.yaml
report.1.yaml
report.2.yaml
```

I think it'd be nice to output multiple domains from the same session into the same file, but I'll revisit that

**Comment by OrlandoMD** [comment]
Hello - this helps!   I'm running the utility with the following batch file listed below to help aggregate results.  

=========================
:  Domain Security Scanner Batch v0.1  8/15/2023 
:  Orlando Stevenson - https://www.linkedin.com/in/orlandostevenson/
: 
:  Loop to read file of domains an execute the windows64 compiled DSS utility 
:  https://github.com/GlobalCyberAlliance/DomainSecurityScanner
:
:
@echo off
SETLOCAL ENABLEDELAYEDEXPANSION
:  Check if the file is provided
if "%~1"=="" (
    echo Please provide list of domains file name
    exit /b
)

IF EXIST merged-report.txt DEL /F merged-report.txt

:  For each line in the input file
for /F "tokens=*" %%A in (%~1) do (
        IF EXIST report.yaml DEL /F report.yaml
	echo %counter% - Working %%A ...
	dss.exe scan %%A -t120 -n1.1.1.1,8.8.8.8 -o report
	type report.yaml >> merged-report.txt	
)
ENDLOCAL

=========================
 
Using batch CLI  comment such as TYPE *.yaml > merged_report.txt could also be used.  I have over a 1000 so  I chose to loop and evaluate each one with its own DSS call.  Doing so has also helped in the past obtain more complete results.

Suggestion: The ability to use the STDOUT approach with ">" would be a helpful improvement.. perhaps eliminating the need for "-o" command line optionn.  

Thank you for updating and enhancing this facility!

Orlando

**Comment by wolveix** [comment]
Hey @OrlandoMD, I've fixed the ability to pipe the output directly :) While the current solution works well for most cases, I still don't like it for bulk usage (at runtime), for example:

```
dss scan globalcyberalliance.org gcatoolkit.org google.com github.com
```

So I may rework it to output an array, but I'm not sold on that idea yet. Hopefully the ability to correctly pipe solves your issues at least!
