### ISSUE TITLE
Option to create Excel CSV file

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/DomainSecurityScanner#14]
Hello,  As a suggestion, consider a "-c" (CSV) option to create output suitable for Excel directly importing or opening as *.csv file.  One row for each domain evaluated, each column for the particular DSS result data type (I've spotted seven at this point), example:
   domain, mx,  spf, dkim, dmarc, bimi, duration  

If there are multiple values for a particular type use something other than comma to concatenate so importing or opening the file in Excel still results with a worksheet having data types consistently in a specific column, e.g., add semicolon ";" for mx results).

I'll be creating a Python parser to help review, create CSV for now.  
This suggestion may help others.

I hope this helps explain.

Respectfully, 

Orlando Stevenson

**Comment by wolveix** [comment]
Hey @OrlandoMD, thanks for the recommendation! I definitely like the idea, and it'd be very easy to implement. I should have time to work on this today, so you may not need to write the Python parser :)

**Comment by wolveix** [comment]
Hey @OrlandoMD, I've just pushed a version with CSV formatting by using the `-f` or `--format` flag. 

I don't like that scanning multiple domains outputs multiple files, but changing that requires solving the question: should we accept domains via STDIN until the user exits, and _then_ we scan the domains and output the results? Do we accept a buffer of a few domains prior to writing the results? What if the buffer is `3` domains but the user only specifies `2`?

Let me know what you think about the CSV implementation anyway!

**Comment by OrlandoMD** [comment]
Hi Robert, Cool - will give the CSV option with "-f" a shot!      As for the multiple output files issue,  any useful approach that will result in a single output file for batch or bulk domain processing will help imho.   There's also the approach of working around the issue with a bit of bash scripting.  A big deal to me is consistent results from one run to the next, or with manual checking, something this new DSS-series of builds seems to do quite well!

**Comment by OrlandoMD** [comment]
Hi Robert, just ran latest status for over 1,000 domains and the CSV option worked very well!
Example -> dss.exe scan -t120 -n1.1.1.1,8.8.8.8 -f csv < domainsin.csv > new_results.csv

Looks like I'll need to retire my batch and Python parser workarounds!

**Comment by wolveix** [comment]
I'm so pleased to hear that, thanks for replying back! We do hope to support bulk processing (when writing to files) in a better way moving forward by writing all of the results to a single file, but we don't have a timeframe to achieve this right now given the concerns raised above. Pull requests are always welcome of course!
