### ISSUE TITLE
Missing dss.exe SPF results?

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/DomainSecurityScanner#15]
Hello - in running the latest DSS.exe build and spot checking with EasyDmarc's [Domain Scanner](https://easydmarc.com/tools/domain-scanner), I noticed that there appears to be SPF information consistently missing in some of the results.

-----------------------------------------------------------------------------------------

**Example 1 - Missing SPF information:**

 **dss scan eisac.com -t120**    
   
scanResult:
    domain: eisac.com
    dmarc: v=DMARC1; p=quarantine; rua=mailto:38daymcb@ag.dmarcian.com, mailto:4f5d1955@mxtoolbox.dmarc-report.com,mailto:it_dmarc_report@eisac.com; ruf=mailto:4f5d1955@forensics.dmarc-report.com,mailto:it_dmarc_report@eisac.com;pct=100
    mx:
        - esa1.nerc.iphmx.com.
        - esa2.nerc.iphmx.com.
    duration: 861.5467ms
    
---  Update 09/07/2023

**EasyDMARC specific SPF results:** 
[https://easydmarc.com/tools/spf-lookup?domain=eisac.com](https://easydmarc.com/tools/spf-lookup?domain=eisac.com)

-----------------------------------------------------------------------------------------
    
**Example 2 - Returns SPF information:**

**dss scan cpi.coop -t120**

scanResult:
    domain: cpi.coop
    dkim: v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCb40a/s7UGrW5XdJqwk6Ins6Maya+tsu4mRKTCSccmY/IFHK4LVW9tInfZobj9y/9UB9grJs4/MywhJvkaN1rKzDsdG03rZv7b4LG/Q386c7MN7/UpbmIEij4c1S7qY0rwS4Czofi68/9TKXA7rgTvK3u4+XoNtEVN096Z2LejDQIDAQAB;
    dmarc: v=DMARC1; p=quarantine; ruf=mailto:majordomo@cpi.coop;
    mx:
        - my-mx.email-protect.gosecure.net.
    spf: v=spf1 mx a:mail.cpi.coop a:mx.cpi.coop a:www.cpi.coop include:spf.sendwp.com include:spf.protection.outlook.com ~all
    duration: 1.1513876s

---  Update 09/07/2023

**EasyDMARC specific SPF results:** [https://easydmarc.com/tools/spf-lookup?domain=cpi.coop](https://easydmarc.com/tools/spf-lookup?domain=cpi.coop)

**Comment by wolveix** [comment]
Hey @OrlandoMD, thanks for opening this issue. It took me a little while to figure out what was going wrong. The underlying library we use to make DNS requests (https://github.com/miekg/dns) makes use of the RFC 1035 spec, which specifies that plain old DNS responses should be 512 bytes. The issue is that `eisac.com`'s TXT records combined consume more than 512 bytes. I've added an override to circumvent this, and will release this shortly.

**Comment by wolveix** [comment]
This should now be fixed. I've added a new commandline option: `dnsBuffer`. I've increased the default buffer from `512` to `1024`, but you can use this option to increase the value if needed. If you experience any further issues, please let me know!
