### ISSUE TITLE
Missing dss.exe DKIM results?

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/DomainSecurityScanner#16]
Hello - in running the latest DSS.exe build and spot checking with EasyDmarc's [Domain Scanner](https://easydmarc.com/tools/domain-scanner), I noticed that there appears to be DKIM information consistently missing in some of the results.

-----------------------------------------------------------------------------------------

**Example 1 - Missing DKIM information:**

 **dss scan eisac.com -t120**    
   
scanResult:
    domain: eisac.com
    dmarc: v=DMARC1; p=quarantine; rua=mailto:38daymcb@ag.dmarcian.com, mailto:4f5d1955@mxtoolbox.dmarc-report.com,mailto:it_dmarc_report@eisac.com; ruf=mailto:4f5d1955@forensics.dmarc-report.com,mailto:it_dmarc_report@eisac.com;pct=100
    mx:
        - esa1.nerc.iphmx.com.
        - esa2.nerc.iphmx.com.
    duration: 1.0038595s
    
-- Update 09/07/2023

**EasyDMARC specific DKIM results (Auto Selector - three identifed):** [https://easydmarc.com/tools/dkim-lookup?domain=eisac.com](https://easydmarc.com/tools/dkim-lookup?domain=eisac.com)
        
-----------------------------------------------------------------------------------------
    
**Example 2 - Returns DKIM information:**

**dss scan adamsec.coop -t120**

scanResult:
scanResult:
    domain: adamsec.coop
    dkim: v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCpqsCqgL3C/vbCe/xBmE4yr6r/V8Hy4aWQB4gBaqPi7n3Et299Pi0DSL1p5Xj6aUCnb60wmCwhDYodvYLw26oHet6BDz43kJnxw9Vwl5XYftQtUHsuMi9kwboZOteofsATkP3wTj+oGgToI9jv+0xUbCmdTCcuE7ZuflqTvV273wIDAQAB; n=1024,1504182604,1
    dmarc: v=DMARC1;p=quarantine;sp=reject;pct=100;fo=1;ruf=mailto:dmarcreports@adamsec.coop;rua=mailto:dmarcreports@adamsec.coop;
    mx:
        - d107315a.ess.barracudanetworks.com.
        - d107315b.ess.barracudanetworks.com.
    spf: v=spf1 include:spf.protection.outlook.com -all
    duration: 813.457ms

-- Update 09/07/2023

**EasyDMARC specific DKIM results (Auto Selector - one identified):** [https://easydmarc.com/tools/dkim-lookup?domain=adamsec.coop](https://easydmarc.com/tools/dkim-lookup?domain=adamsec.coop)

**Comment by wolveix** [comment]
Hey. Due to how DKIM works, DSS makes a best effort attempt to guess the DKIM selector. It's likely that the domains missing the DKIM data are using an uncommon DKIM selector.

I will review this when I'm back in the office to verify that this is indeed the case, but I feel like it most likely is

**Comment by OrlandoMD** [comment]
Hi Robert,

Understood -  thank you for responding!
Interestingly somehow the EasyDMARC Domain Scanner is able to gather and report related status: https://easydmarc.com/tools/domain-scanner
The DSS DMARC-specific status check continues working well.

Respectfully,

Orlando Stevenson

___________________________
Orlando Stevenson<https://www.linkedin.com/in/orlandostevenson/>- PMP, CPP, GCTI, GICSP, GRID, CCSP, CGEIT, ISSAP, CISA, CISM, CISSP, TM-CC, FCC-K9OS - BSCS, MS/MBA
E-ISAC Operations - Senior Cyber Security Analyst
Electricity Information Sharing and Analysis Center
North American Electric Reliability Corporation
1401 H Street NW Suite 400
Washington, DC 20005
202-790-6023 office | 202-360-2365 cell
***@***.******@***.***>
Reliability | Resilience | Security
Twitter @NERC_Official<https://twitter.com/NERC_Official> | LinkedIn<https://www.linkedin.com/company/north-american-electric-reliability-corporation?trk=company_logo>
www.eisac.com<http://www.eisac.com/> | ***@***.******@***.***>, 202-790-6000 (24/7)
***@***.******@***.***> | ***@***.******@***.***> | ***@***.******@***.***>

**Comment by wolveix** [comment]
Hey @OrlandoMD, I've just looked into this. It is indeed due to there not being a recognized DKIM selector. While `selector1` and `selector2` are both present (and are both known), the reason they failed to return anything is similar to #8. It's a CNAME record, rather than a TXT record, which is why DSS doesn't find it (though their `email` selector is a standard TXT record, and I'll add that as a recognized selector).

I'll work on resolving this, thanks for reporting it!

**Comment by wolveix** [comment]
I've added `email` as a known DKIM selector. Thanks again!
