### ISSUE TITLE
go.mod file indicates go 1.17, but maximum supported version is 1.15

### ISSUE THREAD

**Issue by hexclann** [GlobalCyberAlliance/DomainSecurityScanner#4]
Hello, I'm getting an error 

```
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.15
make: *** [Makefile:24: bin/dss] Error 1
```
My golang version is: go1.15.15 linux/amd64

Do i need to update my golang to 1.17?

**Comment by wolveix** [comment]
Yes, per the `go.mod` file, you must have Go 1.17 installed to use build the project. Alternatively, you can find prebuilt releases [here](https://github.com/GlobalCyberAlliance/DomainSecurityScanner/releases).
