### ISSUE TITLE
New docker repository address

### ISSUE THREAD

**Issue by paulohenrique000** [GlobalCyberAlliance/DomainSecurityScanner#5]
Update the [README.md](https://github.com/GlobalCyberAlliance/DomainSecurityScanner#readme) with new address for the docker repository.

**ghcr.io/globalcyberalliance/domainsecurityscanner/domainsecurityscanner:latest**

Reference https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry

**Comment by wolveix** [comment]
Thanks :)
