### ISSUE TITLE
Set Default Nameserver

### ISSUE THREAD

**Issue by henrybelk** [GlobalCyberAlliance/DomainSecurityScanner#7]
Is there a way to set the default nameservers used? It is using Google by default instead of the DNS assigned on the computer that is running it. I block external DNS servers for all clients and have to use '-n x.x.x.x:53' each time I want to scan.

**Comment by wolveix** [comment]
Hey @henrybelk! Thanks for opening this issue.

We don't currently have any configuration as part of the `dss` binary, meaning it's non-trivial to implement this functionality (not that it would be particularly challenging).

Perhaps you could make use of an alias command in your shell? For example, using `bash`, you could add the following line to your `$HOME/.bashrc` file:

```
alias dss="dss -n 9.9.9.9:53"
```

This way, every time you call `dss`, your shell would automatically append the nameserver flag

**Comment by wolveix** [comment]
@henrybelk DSS now supports persistent configurable nameservers. You can configure your own like so:

```
dss config set nameservers 9.9.9.9,1.1.1.1
```
